<?php /* Smarty version 2.6.16, created on 2014-03-21 19:37:53
         compiled from admin.paging.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'admin.paging.tpl', 1, false),array('function', 'math', 'admin.paging.tpl', 15, false),)), $this); ?>
<form method="get" action="" name="paging<?php echo ((is_array($_tmp=$this->_tpl_vars['position'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
">
	<?php $_from = ((is_array($_tmp=$_GET)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
?>
		<?php if (((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'onpage' && ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>
			<input type="hidden" name="<?php echo ((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
" value="<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
" />
		<?php endif; ?>
	<?php endforeach; endif; unset($_from); ?>
	<div class="itemActions">
		<label><?php echo ((is_array($_tmp=$this->_tpl_vars['lang']['admin']['onPage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
:</label>
		<select name="onpage" class="styled" onChange="document.forms['paging<?php echo ((is_array($_tmp=$this->_tpl_vars['position'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
'].submit();">
						<?php $_from = ((is_array($_tmp=$this->_tpl_vars['onPageList'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['curr']):
?>
				<option value="<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
"<?php if (((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=$_GET['onpage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) && ((is_array($_tmp=$_GET['onpage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' || ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=$this->_tpl_vars['Config']['onPage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) && ((is_array($_tmp=$_GET['onpage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ''): ?> selected<?php endif; ?>><?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
</option>
			<?php endforeach; endif; unset($_from); ?>
		</select>
		<?php echo smarty_function_math(array('assign' => 'countFin','equation' => "a + b",'a' => ((is_array($_tmp=$this->_tpl_vars['listInfo']['countSt'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'b' => ((is_array($_tmp=$this->_tpl_vars['listInfo']['onpage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))), $this);?>

		<span><?php echo smarty_function_math(array('equation' => "a + b",'a' => ((is_array($_tmp=$this->_tpl_vars['listInfo']['countSt'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'b' => 1), $this);?>
 - <?php if (((is_array($_tmp=$this->_tpl_vars['countFin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) > ((is_array($_tmp=$this->_tpl_vars['listInfo']['count'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['count'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  else:  echo ((is_array($_tmp=$this->_tpl_vars['countFin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif; ?> <?php echo ((is_array($_tmp=$this->_tpl_vars['lang']['admin']['from'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
 <?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['count'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
</span>
	</div>
</form>
<div class="tPages">
	<ul class="pages">
		<li><a <?php if (((is_array($_tmp=$this->_tpl_vars['listInfo']['prev'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 0): ?> class="paginate_button_disabled" <?php else: ?> href="?mode=<?php echo ((is_array($_tmp=$this->_tpl_vars['adminMode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  if (((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&menu=<?php echo ((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['useInLink'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'page'): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>&page=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['firstpage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['where'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>" <?php endif; ?>><<</a></li>
		<li><a <?php if (((is_array($_tmp=$this->_tpl_vars['listInfo']['prev'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 0): ?> class="paginate_button_disabled" <?php else: ?> href="?mode=<?php echo ((is_array($_tmp=$this->_tpl_vars['adminMode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  if (((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&menu=<?php echo ((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['useInLink'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'page'): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>&page=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['prev'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['where'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>" <?php endif; ?>><</a></li>
		<?php unset($this->_sections['Page']);
$this->_sections['Page']['name'] = 'Page';
$this->_sections['Page']['loop'] = is_array($_loop=((is_array($_tmp=$this->_tpl_vars['listInfo']['pages'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) ? count($_loop) : max(0, (int)$_loop); unset($_loop);
$this->_sections['Page']['show'] = true;
$this->_sections['Page']['max'] = $this->_sections['Page']['loop'];
$this->_sections['Page']['step'] = 1;
$this->_sections['Page']['start'] = $this->_sections['Page']['step'] > 0 ? 0 : $this->_sections['Page']['loop']-1;
if ($this->_sections['Page']['show']) {
    $this->_sections['Page']['total'] = $this->_sections['Page']['loop'];
    if ($this->_sections['Page']['total'] == 0)
        $this->_sections['Page']['show'] = false;
} else
    $this->_sections['Page']['total'] = 0;
if ($this->_sections['Page']['show']):

            for ($this->_sections['Page']['index'] = $this->_sections['Page']['start'], $this->_sections['Page']['iteration'] = 1;
                 $this->_sections['Page']['iteration'] <= $this->_sections['Page']['total'];
                 $this->_sections['Page']['index'] += $this->_sections['Page']['step'], $this->_sections['Page']['iteration']++):
$this->_sections['Page']['rownum'] = $this->_sections['Page']['iteration'];
$this->_sections['Page']['index_prev'] = $this->_sections['Page']['index'] - $this->_sections['Page']['step'];
$this->_sections['Page']['index_next'] = $this->_sections['Page']['index'] + $this->_sections['Page']['step'];
$this->_sections['Page']['first']      = ($this->_sections['Page']['iteration'] == 1);
$this->_sections['Page']['last']       = ($this->_sections['Page']['iteration'] == $this->_sections['Page']['total']);
?>
			<?php if (((is_array($_tmp=$this->_tpl_vars['listInfo']['pages'][$this->_sections['Page']['index']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=$this->_tpl_vars['listInfo']['page'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))): ?>
				<li><a title="" class="active"><?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['pages'][$this->_sections['Page']['index']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
</a></li>
			<?php else: ?>
				<li><a href="?mode=<?php echo ((is_array($_tmp=$this->_tpl_vars['adminMode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  if (((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&menu=<?php echo ((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['useInLink'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'page'): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>&page=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['pages'][$this->_sections['Page']['index']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['where'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>"><?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['pages'][$this->_sections['Page']['index']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
</a></li>			<?php endif; ?>
		<?php endfor; else: ?>
			<?php echo ((is_array($_tmp=$this->_tpl_vars['lang']['admin']['noPages'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>

		<?php endif; ?>
		<li><a <?php if (((is_array($_tmp=$this->_tpl_vars['listInfo']['next'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 0): ?> class="paginate_button_disabled" <?php else: ?> href="?mode=<?php echo ((is_array($_tmp=$this->_tpl_vars['adminMode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  if (((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&menu=<?php echo ((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['useInLink'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'page'): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>&page=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['next'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['where'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>" <?php endif; ?>>></a></li>
		<li><a <?php if (((is_array($_tmp=$this->_tpl_vars['listInfo']['next'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 0): ?> class="paginate_button_disabled" <?php else: ?> href="?mode=<?php echo ((is_array($_tmp=$this->_tpl_vars['adminMode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  if (((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&menu=<?php echo ((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['useInLink'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'page'): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>&page=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo']['lastpage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['where'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['curr']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from); ?>" <?php endif; ?>>>></a></li>
	</ul>
</div>
<div class="clear"></div>