<?php /* Smarty version 2.6.16, created on 2014-03-21 19:37:53
         compiled from admin.linktoitem.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'admin.linktoitem.tpl', 9, false),)), $this); ?>
<a href="index.php?mode=<?php echo ((is_array($_tmp=$this->_tpl_vars['Mode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  if (((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&menu=<?php echo ((is_array($_tmp=$this->_tpl_vars['menu'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif; ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['WorkTableKeyVarName'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'][$this->_tpl_vars['WorkTableKeyFieldName']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['useInLink'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['curr']):
 if (((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '' && ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'pmode'): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['curr'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['listInfo'][$this->_tpl_vars['curr']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from);  $_from = ((is_array($_tmp=$this->_tpl_vars['listInfo']['where'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['current']):
 if (((is_array($_tmp=$this->_tpl_vars['current']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&<?php echo ((is_array($_tmp=$this->_tpl_vars['key'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
=<?php echo ((is_array($_tmp=$this->_tpl_vars['current']['value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif;  endforeach; endif; unset($_from);  if (((is_array($_tmp=$this->_tpl_vars['adminMode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ''): ?>&pmode=<?php echo ((is_array($_tmp=$this->_tpl_vars['adminMode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  endif; ?>" class="tablectrl_small bDefault tipS" title="<?php echo ((is_array($_tmp=$this->_tpl_vars['lang']['admin']['edit'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
"><span class="buttonTemp icos-pencil"></span></a>